
package br.com.kohen.eventmanager.clarion.ws.wsdl.balance;

import br.com.kohen.eventmanager.clarion.ws.WSConfig;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WSCLSE5SOAP", targetNamespace = WSConfig.WS_END_POINT)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSCLSE5SOAP {


    /**
     * 
     * @param chave
     * @param pedido
     * @param empresa
     * @param parcela
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SALDOTITULO", action = WSConfig.WS_END_POINT + "SALDOTITULO")
    @WebResult(name = "SALDOTITULORESULT", targetNamespace = WSConfig.WS_END_POINT)
    @RequestWrapper(localName = "SALDOTITULO", targetNamespace = WSConfig.WS_END_POINT, className = "stubs.SALDOTITULO")
    @ResponseWrapper(localName = "SALDOTITULORESPONSE", targetNamespace = WSConfig.WS_END_POINT, className = "stubs.SALDOTITULORESPONSE")
    public String saldotitulo(
        @WebParam(name = "CHAVE", targetNamespace = WSConfig.WS_END_POINT)
        String chave,
        @WebParam(name = "EMPRESA", targetNamespace = WSConfig.WS_END_POINT)
        String empresa,
        @WebParam(name = "PEDIDO", targetNamespace = WSConfig.WS_END_POINT)
        String pedido,
        @WebParam(name = "PARCELA", targetNamespace = WSConfig.WS_END_POINT)
        String parcela);

}
