
package br.com.kohen.eventmanager.clarion.ws.wsdl.company;

import br.com.kohen.eventmanager.clarion.ws.WSConfig;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "WSCLSA1", targetNamespace = WSConfig.WS_END_POINT, wsdlLocation = WSConfig.WS_END_POINT + "ws/wsclsa1.apw?wsdl")
public class WSCLSA1
    extends Service
{

    private final static URL WSCLSA1_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(WSCLSA1 .class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = br.com.kohen.eventmanager.clarion.ws.wsdl.company.WSCLSA1 .class.getResource(".");
            url = new URL(baseUrl, WSConfig.WS_END_POINT +  "ws/wsclsa1.apw?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://179.191.78.118:81/ws/wsclsa1.apw?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        WSCLSA1_WSDL_LOCATION = url;
    }

    public WSCLSA1(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSCLSA1() {
        super(WSCLSA1_WSDL_LOCATION, new QName(WSConfig.WS_END_POINT, "WSCLSA1"));
    }

    /**
     * 
     * @return
     *     returns WSCLSA1SOAP
     */
    @WebEndpoint(name = "WSCLSA1SOAP")
    public WSCLSA1SOAP getWSCLSA1SOAP() {
        return super.getPort(new QName(WSConfig.WS_END_POINT, "WSCLSA1SOAP"), WSCLSA1SOAP.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSCLSA1SOAP
     */
    @WebEndpoint(name = "WSCLSA1SOAP")
    public WSCLSA1SOAP getWSCLSA1SOAP(WebServiceFeature... features) {
        return super.getPort(new QName(WSConfig.WS_END_POINT, "WSCLSA1SOAP"), WSCLSA1SOAP.class, features);
    }

}
