
package br.com.kohen.eventmanager.clarion.ws.wsdl.purchase;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "WSCLSC5SOAP", targetNamespace = "http://189.2.170.19:81/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSCLSC5SOAP {


    /**
     * 
     * @param pedido
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GRAVADADOS", action = "http://189.2.170.19:81/GRAVADADOS")
    @WebResult(name = "GRAVADADOSRESULT", targetNamespace = "http://189.2.170.19:81/")
    @RequestWrapper(localName = "GRAVADADOS", targetNamespace = "http://189.2.170.19:81/", className = "br.com.kohen.eventmanager.plugin.clarion.wsdl.purchase.GRAVADADOS")
    @ResponseWrapper(localName = "GRAVADADOSRESPONSE", targetNamespace = "http://189.2.170.19:81/", className = "br.com.kohen.eventmanager.plugin.clarion.wsdl.purchase.GRAVADADOSRESPONSE")
    public String gravadados(
        @WebParam(name = "PEDIDO", targetNamespace = "http://189.2.170.19:81/")
        APEDIDO pedido);

}
