
package br.com.kohen.eventmanager.clarion.ws.wsdl.purchase;

import br.com.kohen.eventmanager.clarion.ws.WSConfig;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * Compilado em 10/09/13 as 12:01
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "WSCLSC5", targetNamespace = WSConfig.WS_END_POINT, wsdlLocation = WSConfig.WS_END_POINT + "ws/WSCLSC5.apw?WSDL")
public class WSCLSC5 extends Service {

    private final static URL WSCLSC5_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(WSCLSC5.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = WSCLSC5.class.getResource(".");
            url = new URL(baseUrl, WSConfig.WS_END_POINT + "ws/WSCLSC5.apw?WSDL");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://189.2.170.19:81/ws/WSCLSC5.apw?WSDL', retrying as a local file");
            logger.warning(e.getMessage());
        }
        WSCLSC5_WSDL_LOCATION = url;
    }

    public WSCLSC5(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSCLSC5() {
        super(WSCLSC5_WSDL_LOCATION, new QName(WSConfig.WS_END_POINT, "WSCLSC5"));
    }

    /**
     * 
     * @return
     *     returns WSCLSC5SOAP
     */
    @WebEndpoint(name = "WSCLSC5SOAP")
    public WSCLSC5SOAP getWSCLSC5SOAP() {
        return super.getPort(new QName(WSConfig.WS_END_POINT, "WSCLSC5SOAP"), WSCLSC5SOAP.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSCLSC5SOAP
     */
    @WebEndpoint(name = "WSCLSC5SOAP")
    public WSCLSC5SOAP getWSCLSC5SOAP(WebServiceFeature... features) {
        return super.getPort(new QName(WSConfig.WS_END_POINT, "WSCLSC5SOAP"), WSCLSC5SOAP.class, features);
    }

}
