
package br.com.kohen.eventmanager.clarion.ws.wsdl.purchase;

import br.com.kohen.eventmanager.clarion.ws.WSConfig;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "WSCLSC5SOAP", targetNamespace = WSConfig.WS_END_POINT)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSCLSC5SOAP {


    /**
     * 
     * @param pedido
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GRAVADADOS", action = WSConfig.WS_END_POINT + "GRAVADADOS")
    @WebResult(name = "GRAVADADOSRESULT", targetNamespace = WSConfig.WS_END_POINT)
    @RequestWrapper(localName = "GRAVADADOS", targetNamespace = WSConfig.WS_END_POINT, className = "purchase.GRAVADADOS")
    @ResponseWrapper(localName = "GRAVADADOSRESPONSE", targetNamespace = WSConfig.WS_END_POINT, className = "purchase.GRAVADADOSRESPONSE")
    public String gravadados(
        @WebParam(name = "PEDIDO", targetNamespace = WSConfig.WS_END_POINT)
        APEDIDO pedido);

}
