
package br.com.kohen.eventmanager.clarion.ws.wsdl.purchase;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "WSCLSC5", targetNamespace = "http://189.2.170.19:81/", wsdlLocation = "http://189.2.170.19:81/ws/wsclsc5.apw?wsdl")
//@Component("purchaseWSService")
public class WSCLSC5
    extends Service
{

    private final static URL WSCLSC5_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(br.com.kohen.eventmanager.clarion.ws.wsdl.purchase.WSCLSC5 .class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = br.com.kohen.eventmanager.clarion.ws.wsdl.purchase.WSCLSC5 .class.getResource(".");
            url = new URL(baseUrl, "http://189.2.170.19:81/ws/wsclsc5.apw?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://189.2.170.19:81/ws/wsclsc5.apw?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        WSCLSC5_WSDL_LOCATION = url;
    }

    public WSCLSC5(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSCLSC5() {
    	super(WSCLSC5_WSDL_LOCATION, new QName("http://189.2.170.19:81/", "WSCLSC5"));
     }

    /**
     * 
     * @return
     *     returns WSCLSC5SOAP
     */
    @WebEndpoint(name = "WSCLSC5SOAP")
    public WSCLSC5SOAP getWSCLSC5SOAP() {
        return super.getPort(new QName("http://189.2.170.19:81/", "WSCLSC5SOAP"), WSCLSC5SOAP.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSCLSC5SOAP
     */
    @WebEndpoint(name = "WSCLSC5SOAP")
    public WSCLSC5SOAP getWSCLSC5SOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://189.2.170.19:81/", "WSCLSC5SOAP"), WSCLSC5SOAP.class, features);
    }

}
